### ISSUE TITLE
Gadget-queryContributions 支持查询通过 GHIA 做出的编辑

### ISSUE THREAD

**Issue by AnnAngela** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#147]
RT

**Comment by lovelyCARDINAL** [comment]
如果用户名在[贡献列表](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/master/.mailmap)，读取AnnAngela-dbot全部贡献，数以`by [[U:{username}]]`结尾的数量？

要不要把编辑定义页的摘要也改成以`by [[U:{username}]]`结尾的格式

**Comment by lovelyCARDINAL** [comment]
> 要不这样，既然你有统计，我直接从统计表里拿就好了
机器人只统计指定用户组、指定时间段的来着，统计全部也行，回头看看怎么弄方便

**Comment by AnnAngela** [comment]
@lovelyCARDINAL 定义页已经有这个了，你调整一下正则就行


![Image](https://user-images.githubusercontent.com/9762652/229010852-20ca30a3-e581-43e7-a4d9-98f80fe0ab06.png)

**Comment by BearBin1215** [comment]
> @lovelyCARDINAL 定义页已经有这个了，你调整一下正则就行
> 
> ![Image](https://user-images.githubusercontent.com/9762652/229010852-20ca30a3-e581-43e7-a4d9-98f80fe0ab06.png)

如果一个pr有多名贡献者，这个是不是就只会显示最后的了

**Comment by AnnAngela** [comment]
> 如果一个pr有多名贡献者，这个是不是就只会显示最后的了

算 commit 的，多个 commit 会一并显示
![image](https://user-images.githubusercontent.com/9762652/229017658-11ded6f7-4566-44ce-8e6a-40b40328ecf8.png)

**Comment by BearBin1215** [comment]
![104.png](https://user-images.githubusercontent.com/20369414/229018585-cc8251ca-a2d9-4e04-87a0-bfcbff0ebe16.png)
但比如这个好像没有显示？#104我和星海都有commit

**Comment by AnnAngela** [comment]
>#104我和星海都有commit

哦你是说文件是吧，那可能没有，每次提交只会表露最后一次编辑的 commit。看来需要另辟蹊径了

**Comment by AnnAngela** [comment]
我想到了，用workflow生成一个json存到萌百就行了，不用机器人弄

**Comment by lovelyCARDINAL** [comment]
能不能额外存一个365日内的版本
省的我机器人读摘要

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by AnnAngela** [comment]
LGTM
![image](https://user-images.githubusercontent.com/9762652/229131341-2573bad6-d22f-4be9-8c92-723ded08947e.png)
