### ISSUE TITLE
Echarts

### ISSUE THREAD

**Issue by lovelyCARDINAL** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#151]
目前有[一个widget](https://zh.moegirl.org.cn/Widget:Echart)和一个[小工具](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/tree/master/src/gadgets/queryContributions)在使用echarts，但版本不一样
建议将echarts库引入站点小工具，自动更新，以避免可能存在的jsdelivr访问困难问题

**Comment by AnnAngela** [comment]
已添加 echarts 4 和 5，需要观察是否生效（比如加载了但没有在 `window` 里导出）
还需要考虑是否将 widget:Echarts 也改为 echarts 5，这样就能避免版本冲突

**Comment by AnnAngela** [comment]
由于echarts过大无法保存到站内，改用饿了么cdn加载
