### ISSUE TITLE
autoconfirmedUserPing

### ISSUE THREAD

**Issue by lovelyCARDINAL** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#157]
当前版本无法判断封禁记录，获取的列表有误
- [x] u.registration 改为33天，因为成为自确至少还需要3天。
- [ ] 增加判断提案发起时到现在，是否存在封禁记录（含封禁到期在此时间段内、封禁发起在此时间段内，并且可能需要忽略滥用过滤器封禁）

**Comment by AnnAngela** [comment]
“并且可能需要忽略滥用过滤器封禁”，得区分哪个吧
