### ISSUE TITLE
关于 GHIAHistory.json

### ISSUE THREAD

**Issue by lovelyCARDINAL** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#190]
- [x] 将datetime统一为UTC
- [x] 检查co-author是否能被正确统计/或pr是否只统计最后一个author

**Comment by lovelyCARDINAL** [comment]
好像只能去找包含Co-authored-by字符串的commit `/Co-authored-by: (.*) <(.*)>/gi`

**Comment by AnnAngela** [comment]
Fixed in bbd1b5d...31b4024
