### ISSUE TITLE
require(5) → Error: Module "5" is not loaded.

### ISSUE THREAD

**Issue by Xzonn** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#3]
<https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/master/src/gadgets/cron/MediaWiki:Gadget-cron.js#L744>
``` javascript
		_$cron_2 = factory(require(5), _$_empty_1({}));
```
这个`require(5)`似乎导致报错：`Error: Module "5" is not loaded.`，目前右上角清除缓存的按钮消失了。
@AnnAngela

**Comment by AnnAngela** [comment]
经查，browserify 的 common-shakeify 插件会导致 cron 所依赖的 luxon 整个被削除，我还在查找看如何解决（实在不行就对 cron 禁用这个插件好了）

**Comment by AnnAngela** [comment]
Fix in f3cb7fe
