### ISSUE TITLE
code-prettify无法正确高亮wikitext

### ISSUE THREAD

**Issue by bhsd-harry** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#435]
googlearchive/code-prettify库中定义的wikitext[并不是mediawiki](https://github.com/googlearchive/code-prettify/blob/master/src/lang-wiki.js)。

**Comment by AnnAngela** [comment]
居然不是吗，有啥差别

**Comment by bhsd-harry** [comment]
> 居然不是吗，有啥差别

这里的wikitext指的是Google Code当年自己开发的一种[标记语言](https://code.google.com/archive/p/google-code-wiki-to-html/)，目前网上已很难找到具体介绍。

**Comment by gui-ying233** [comment]
[H:代码高亮工具](//zh.moegirl.org.cn/H:代码高亮工具) 是否需要同步改一下（

**Comment by lovelyCARDINAL** [comment]
那你改一下?

**Comment by bhsd-harry** [comment]
是否考虑更换其他支持高亮wikitext的库，比如[Prism](https://prismjs.com)？

**Comment by AnnAngela** [comment]
https://prismjs.com/known-failures.html#wiki

emmm不是很好用的样子

**Comment by bhsd-harry** [comment]
> https://prismjs.com/known-failures.html#wiki
> 
> emmm不是很好用的样子

那要不要试试我魔改的版本？

```js
window.Prism ||= {}.
Prism.parserConfig = await (await fetch('//cdn.jsdelivr.net/npm/wikiparser-node@browser/config/moegirl.json')).json();
mw.loader.load('//cdn.jsdelivr.net/npm/prism-wiki');
```

我用的wikitext高亮库已经历上千条[测试](https://bhsd-harry.github.io/wikiparser-node/tests.html)。

**Comment by AnnAngela** [comment]
@bhsd-harry 能不能整成能放进gadget的形式

**Comment by bhsd-harry** [comment]
于#443、#446、#451 完成。
