### ISSUE TITLE
打回工具更新

### ISSUE THREAD

**Issue by lovelyCARDINAL** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#480]
1. 返回提交到审核队列时判定为success
2. 修改移动摘要包含 不留重定向 字样使能被机器人自动删除
3. 修改提醒用户的文本

**Comment by lovelyCARDINAL** [comment]
@AnnAngela 能不能帮忙看看，返回提交到审核队列时判定为success，但是如果已在审核队列返回error
其他大概改好了，在打回分支

**Comment by lovelyCARDINAL** [comment]
机器人删除重定向改成了2小时一次先、

**Comment by gui-ying233** [comment]
> > @AnnAngela 能不能帮忙看看，返回提交到审核队列时判定为success，但是如果已在审核队列返回error 其他大概改好了，在打回分支
> 
> 怎么判断在审核队列来着

https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/ca2e70d9438a84d98cb87dfb5a9976af7145e72b/src/gadgets/ModerationStatus/MediaWiki%3AGadget-ModerationStatus.js#L35-L47

**Comment by AnnAngela** [comment]
那 @lovelyCARDINAL 你弄个 pr 我给你加上

**Comment by lovelyCARDINAL** [comment]
#482

**Comment by lovelyCARDINAL** [comment]
完事了可以拿[[[厄斯公国](https://zh.moegirl.org.cn/%E5%8E%84%E6%96%AF%E5%85%AC%E5%9B%BD)]]页面测试打回
