### ISSUE TITLE
MediaWiki:Gadget-prism-coy.css 没过 linter

### ISSUE THREAD

**Issue by AnnAngela** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#490]
[MediaWiki:Gadget-prism-coy.css](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/actions/runs/9473941530#:~:text=by%20humans.txt-,Annotations,-10%20errors)

@bhsd-harry 佬改一下

**Comment by bhsd-harry** [comment]
@AnnAngela 这是直接从[PrismJS](https://github.com/PrismJS/prism/blob/master/themes/prism-coy.css)获取的CSS，按理应该被忽略，我不太理解 c0a69afe6366356230931aa193c68075115145be

**Comment by AnnAngela** [comment]
> @AnnAngela 这是直接从[PrismJS](https://github.com/PrismJS/prism/blob/master/themes/prism-coy.css?rgh-link-date=2024-06-12T04%3A16%3A02Z)获取的CSS，按理应该被忽略，我不太理解 [c0a69af](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/commit/c0a69afe6366356230931aa193c68075115145be)

哦，是因为<https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/commit/822bde45a95f7289c9553c8f2ad5fd6bc2109c2f#diff-ac00eed3007c328a3477d00960167fd58a78081e9e00a9657f5e3ad29d79a3c4L33-L40>，这里把coy删了，导致bot以为这个css不再是机器生成了。我加一下吧。
