### ISSUE TITLE
萌皮移动版下class=navbox的表格显示错位

### ISSUE THREAD

**Issue by gui-ying233** [MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes#555]
>[【BUG】萌皮移动版下class=navbox的表格显示错位](https://zh.moegirl.org.cn/_?curid=543139#【BUG】萌皮移动版下class=navbox的表格显示错位) 
> —— @C8H17OH

https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/7b6807a5c3dd5829bddac57140fb60cf99554d85/src/gadgets/moeskin-styles/MediaWiki%3AGadget-moeskin-styles.css#L138-L140
这一段的意义是什么？没问题的话就删了吧（

**Comment by dragon-fish** [comment]
@lovelyCARDINAL 我也不知道这个是干嘛的

**Comment by lovelyCARDINAL** [comment]
那能删掉吗

**Comment by dragon-fish** [comment]
你加的，我不知道啊
